### PR TITLE
Parse generics

### PR DESCRIPTION
**Pull request by 8BitMate**
This pull request is for parsing generics in the library macro. I tried to limit the scope, but it turned out a bit more comprehensive than anticipated. There are still some rough corners here and there, and there are no logic that deals with trait resolution, so the output from the compiler is incorrect when dealing with generics. I also have yet to support parsing of associated types in traits.

Other than that, I think the parsing works as intended.

### CODE REVIEW

**Comment by davidbarsky** [comment]
@8BitMate Would it be okay if I tried out this branch and gave feedback? I'm not sure what the timeline of that would be, though.

**Comment by 8BitMate** [comment]
@davidbarsky You may try it out if you want. I'm trying to finish some basic trait inference at the moment. Hopefully I'm getting close, but I have thought that for a while now, so I'm not sure if it's entirely true. If you want to give feedback it might be more fruitful to wait until that is done, as the rest of the code might make more sense then. I also plan on removing some code which I only intended to be temporary. You may feel free to check out the code that is already there if you want to, though.

**Comment by 8BitMate** [comment]
@davidbarsky Hi, sorry for the long wait, but I've now implemented some basic trait and type inference into the compiler, which at least works for the cases I've tested them with. If you still want to try out this branch, now is a good time. I'm sure there are still bugs, and I know the code generation is sometimes wrong, but code generation is unrelated to the issue of traits and generics. Also a quick note about lifetimes. I've basically not thought about how to deal with them for now, so if you try to do something fancy with references and lifetimes, it will probably be incorrect, and if it is correct, it is by accident and not by design.

**Comment by eupn** [comment]
Nice job!

**Comment by davidbarsky** [comment]
@8BitMate No worries about the wait! I wasn't in any rush :). I'm really glad to see this feature come along!

**Comment by 8BitMate** [comment]
I think I am ready to merge this pull request into the master branch. Although there are things it cannot do yet in terms of generics, it can parse and reason with generic types and trait bounds. In summary this pull request adds:

- Parsing generic types traits and impls in the `library!` macro.
- Inferring types and trait bounds for generic parameters when implementing a trait.
- inferring lifetime subtype relationships between lifetime parameters.
In some cases it can infer that a lifetime parameter has to be 'static. At the moment it does not add lifetime bounds to types, but this may be added in the future.
- Redesigning how global data is stored in the program.
I ran upon some limitations on the previous design when implementing the `trait_inference` module, so I changed it.
- Referencing types not inside the current module in the `library!` macro.
- Small fix in the code generation for destructures.
- Many small changes and fixes, that I probably have forgotten.

Things that have yet to be implemented:
- Associated types.
- Self types.

It also removes the following functionality:
- RuntimeType impls are not generated inside the `library!` macro.
This means you cannot call `RUNTIME::some_crate::some_module::MyType.SELF()`. The reason I removed this is because I haven't figured out how to integrate generic types that are not bound to anything. I'm not sure how this would integrate with the current inference methods. I don't think this is a major issue, although the functionality would be nice to have.

Other than that the functionality should be more or less the same.

**Comment by eupn** [comment]
Terrific!

**Comment by dtolnay** [comment]
This is terrific work!

I was thinking since you've now written more of the code than I have, and I'm not going to have bandwidth to stay deeply involved, it would also be reasonable to make https://github.com/8BitMate/reflect the canonical repo for this project with ongoing development, and in mine instead of updating master we could put a big link to your repo in the readme.

**Comment by 8BitMate** [comment]
Woops, I already merged it. I could revert the pull request if you want. Or if it doesn't matter, leave it as it is, and then link to https://github.com/8BitMate/reflect as you said.

**Comment by dtolnay** [comment]
To be a little more clear I'm not *requesting* that we move development to your repo, just suggesting to consider it because you've done most of the work at this point so I think it makes sense, but I meant to leave it up to your preference.

If you do prefer for https://github.com/8BitMate/reflect to be the canonical repo for the project then I would slightly lean toward force-pushing master back the the parent of this merge commit so that your repo immediately has a clear advantage for people. I'll also give publish access to the `reflect` name on crates.io, and you should update the metadata in Cargo.toml to point to your repository.

**Comment by 8BitMate** [comment]
I think I might prefer to have it in my own repo, but I'm not entirely sure how to force push the old master branch back up. I already pulled the latest changes from master locally. Thanks for giving me publish access btw :slightly_smiling_face: I haven't published anything on crates.io yet, so I'm not yet sure how it works.

**Comment by dtolnay** [comment]
Okay I took care of the force push.

The publish process is documented here: https://doc.rust-lang.org/cargo/reference/publishing.html

**Pull request merged**
